# Configuration file for fontmake

sources:
  - path: Parkinsans_AW_Google.glyphs
    familyName: Parkinsans
    styleName: Regular
    weight: 400
  - path: Parkinsans_AW_Google.glyphs
    familyName: Parkinsans
    styleName: Light
    weight: 300
  - path: Parkinsans_AW_Google.glyphs
    familyName: Parkinsans
    styleName: Semibold
    weight: 600
  - path: Parkinsans_AW_Google.glyphs
    familyName: Parkinsans
    styleName: Bold
    weight: 700
  - path: Parkinsans_AW_Google.glyphs
    familyName: Parkinsans
    styleName: Extrabold
    weight: 800

output:
  variable: false  # Set to true if you want to create a variable font
  static: true
  formats:
    - ttf  # Add other formats if needed, e.g., otf

instances:
  - familyName: Parkinsans
    styleName: Regular
    location:
      wght: 400
  - familyName: Parkinsans
    styleName: Light
    location:
      wght: 300
  - familyName: Parkinsans
    styleName: Semibold
    location:
      wght: 600
  - familyName: Parkinsans
    styleName: Bold
    location:
      wght: 700
  - familyName: Parkinsans
    styleName: Extrabold
    location:
      wght: 800

# Optional settings can go here
